### ISSUE TITLE
Inf and Nan in pseduo R2 and residuals using beta family glm

### ISSUE THREAD

**Issue by katiewampler** [USEPA/SSN2#23] opened 2024-08-06 17:59 UTC
I'm using the beta family glm SSN models, and for some (but not all) models, when I get the model statistics the pseduo R2 and residuals are missing/Nan/Inf/NA.

I was able to track down the code causing the issue: in the get_deviance_glm function, the gamma function was returning Inf values when above ~171. Some of my values where above this and returning Inf values. 

It appeared using a modified function: 
 constant <- log(gamma(fitted_response * dispersion)) +  
      as.numeric(log(Rmpfr::igamma(((1 - fitted_response) * dispersion), 0))) - 
      log(gamma(y * dispersion)) - as.numeric(log(Rmpfr::igamma(a=((1 - y) * 
                                                                     dispersion),x=0))) fixed the issue. 

Here's the code I used which produced the error:
library(SSN2)
library(sf)
library(dplyr)

ssn <- ssn_import("~/1_Research/5_McKenzie_EEMs/data/parafac_ssn/lsn.ssn") #load SSN
df<- ssn_get_data(ssn)
df[,6:11] <- sapply(df[,6:11] %>%st_drop_geometry(), function(x){x/100}) #convert to a fraction
ssn <- ssn_put_data(df, ssn) #put converted data in model
mod <- ssn_glm(Comp_1 ~ DNBR + Season, ssn, family="beta",
               tailup_type = "none",
               taildown_type = "none",
               euclid_type = "none", 
               additive = "afvArea",
               random=~Site)
summary(mod)
[lsn.ssn.zip](https://github.com/user-attachments/files/16514085/lsn.ssn.zip)

**Comment by michaeldumelle** [comment] 2024-08-16 15:14
Thanks @katiewampler ! I identified the numerical problem (with help from you) and implemented a stability update ([linked here](https://github.com/USEPA/SSN2/commit/a3f2f6691270db789585e1d35d4186a0b6d319d9)).

The code is working as intended now on the development branch of `SSN2`, which you can download by running

```r
remotes::install_github("USEPA/SSN2", ref = "develop")
```

This update will be part of the next CRAN release (the current version on CRAN is 0.2.0), which should up before the end of the year.

It's worth noting that I also implemented this stability update for [spmodel](https://usepa.github.io/spmodel/).

**Closed as completed by michaeldumelle** 2024-08-16 15:14 UTC
